// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ArticleBrief {
  id: string;
  title: string;
}

export function AnswerFollow(arg1: string, arg2: string, arg3: boolean): Promise<void>;

export function CreateArticle(arg1: string): Promise<string>;

export function DeleteLine(arg1: string): Promise<void>;

export function Join(arg1: string, arg2: string): Promise<void>;

export function ListArticles(): Promise<Array<ArticleBrief>>;

export function MergeUp(arg1: string): Promise<void>;

export function MoveCaret(arg1: string, arg2: string, arg3: number, arg4: number): Promise<void>;

export function PersonID(): Promise<string>;

export function RequestFollow(arg1: string): Promise<void>;

export function SetServer(arg1: string): Promise<void>;

export function SubmitEdit(arg1: string, arg2: string): Promise<void>;

export function SubmitInsert(arg1: string, arg2: string[]): Promise<void>;

export function SubmitPaste(arg1: string, arg2: string[]): Promise<void>;

export function Suspend(arg1: string, arg2: string, arg3: boolean): Promise<void>;
