// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnswerFollow(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnswerFollow'](arg1, arg2, arg3);
}

export function CreateArticle(arg1) {
  return window['go']['main']['App']['CreateArticle'](arg1);
}

export function DeleteLine(arg1) {
  return window['go']['main']['App']['DeleteLine'](arg1);
}

export function DismissUnsynced(arg1) {
  return window['go']['main']['App']['DismissUnsynced'](arg1);
}

export function GetCachedArticle() {
  return window['go']['main']['App']['GetCachedArticle']();
}

export function GetSaveWarning() {
  return window['go']['main']['App']['GetSaveWarning']();
}

export function GetServer() {
  return window['go']['main']['App']['GetServer']();
}

export function Join(arg1, arg2) {
  return window['go']['main']['App']['Join'](arg1, arg2);
}

export function ListArticles() {
  return window['go']['main']['App']['ListArticles']();
}

export function ListUnsynced() {
  return window['go']['main']['App']['ListUnsynced']();
}

export function MergeUp(arg1) {
  return window['go']['main']['App']['MergeUp'](arg1);
}

export function MoveCaret(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MoveCaret'](arg1, arg2, arg3, arg4);
}

export function MoveCaretRange(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['MoveCaretRange'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function PersonID() {
  return window['go']['main']['App']['PersonID']();
}

export function ReportError(arg1, arg2) {
  return window['go']['main']['App']['ReportError'](arg1, arg2);
}

export function RejectClaim(arg1) {
  return window['go']['main']['App']['RejectClaim'](arg1);
}

export function RequestFollow(arg1) {
  return window['go']['main']['App']['RequestFollow'](arg1);
}

export function SetServer(arg1) {
  return window['go']['main']['App']['SetServer'](arg1);
}

export function SubmitEdit(arg1, arg2) {
  return window['go']['main']['App']['SubmitEdit'](arg1, arg2);
}

export function SubmitEditClaim(arg1, arg2) {
  return window['go']['main']['App']['SubmitEditClaim'](arg1, arg2);
}

export function SubmitInsert(arg1, arg2) {
  return window['go']['main']['App']['SubmitInsert'](arg1, arg2);
}

export function SubmitInsertBefore(arg1, arg2) {
  return window['go']['main']['App']['SubmitInsertBefore'](arg1, arg2);
}

export function SubmitPaste(arg1, arg2) {
  return window['go']['main']['App']['SubmitPaste'](arg1, arg2);
}

export function SubmitSpanEdit(arg1, arg2, arg3) {
  return window['go']['main']['App']['SubmitSpanEdit'](arg1, arg2, arg3);
}

export function Suspend(arg1, arg2, arg3) {
  return window['go']['main']['App']['Suspend'](arg1, arg2, arg3);
}
